### ISSUE TITLE
Ubuntuではウィンドウ枠が表示されません

### ISSUE THREAD

**Issue by seishun** [nekopanda/logbook#19]
下手な日本語で申し訳ありません。

Ubuntu 14.04.2を使っています。ppa:webupd8team/javaからのoracle-java8-installerをインストールしました。航海日誌拡張版1.7.0betaを起動すると、ウィンドウ枠が表示されません。

![こう見えます](http://i.snag.gy/5bmj0.jpg)

@sanae_hirotakaさんの航海日誌は問題ありません。

何か解決方法はありますか？よろしくお願いします。

**Comment by nekopanda** [comment]
報告ありがとうございます。a770be04087ca88e097549c9109215d3bf63c8a8 で修正しました
