### ISSUE TITLE
立ち上げするとscriptがデフォルトの物に上書きされる、外

### ISSUE THREAD

**Issue by pokemonleo** [nekopanda/logbook#22]
はじめまして
航海日誌拡張版をありがたく使わせて頂いてます

1、scriptの下にデフォルトから変更施したものが置いてあっても、航海日誌を立ち上げする毎にデフォルトの物に上書きされるんですが仕様でしょうか？（バグ？）

2、templateにあるbattle-log.cssも自分好みに変更してあったので、航海日誌がアップデートする毎に（zipファイル内容を全部コピーして貼り付けすると一緒にデフォルトの物に）上書きされるので別途バックアップ取らなきゃなりません。scriptみたいにデフォルトのファイルと現行使用しているファイルを別々にすることができませんか？battle-log.cssが存在しなかったらbattle-log-default.cssを読み込むとか（要望）

3、戦況ウィンドウは最小化している間は戦況ウィンドウのレンダリングは更新しなくなりますが仕様であってますか？（ログは最小化していても問題なく出力します）

Win7 x64 1.7.7使ってます
ありがとうございます

**Comment by nekopanda** [comment]
ver1.8.1で修正しました。関連コミット: 8814cb3435dccf63da2e6af56f54a83334370024

1. 更新日時を見てtemplatesにあるスクリプトの方が新しい場合は上書きするようになっていたのですが、gitでブランチを切り替えたりすると更新日時が新しくなってしまってうまく機能していませんでした。`ignore_update.txt`で更新から除外するスクリプトの指定ができるようにしました。 [解説ページ](https://github.com/nekopanda/logbook/wiki/Extend-with-JavaScript#%E5%90%8C%E6%A2%B1%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88%E3%81%AE%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E6%8A%91%E5%88%B6)

2. `template/battle-log.css`は`config/battle-log.css`にコピーして使用するようにしました。configにないときだけtemplatesをコピーしますい。configにある時は上書きしません。 

3. 航海日誌を最小化していると戦況ウィンドウが更新されない不具合も修正しました。

**Comment by pokemonleo** [comment]
お疲れ様です！

早速使ってみました。今のところ修正した箇所は問題ないみたいです
ありがとうございました！
