### ISSUE TITLE
BattleEx displays incorrectly

### ISSUE THREAD

**Issue by austringer** [nekopanda/logbook#35]
![20150905042712](https://cloud.githubusercontent.com/assets/3364858/9693875/69228952-5386-11e5-8dc8-793e3c89cce3.png)
The star shell user in combined fleet shows incorrectly in BattleEx. The flagship Prinz Eugen in fleet 2 fires the star shell, while Taihou is the flagship of fleet 1.

**Comment by nekopanda** [comment]
Fixed. dc71f3695aec556fbf45f49948056e0b81f00095
