### ISSUE TITLE
regarding the no responds after update

### ISSUE THREAD

**Issue by ccxcxd** [nekopanda/logbook#38]
翔鶴改二(api_id=461)'s api_aftershipid is 翔鶴改二甲(api_id=466)
翔鶴改二甲's api_aftershipid is 翔鹤改二

改造最終艦のID has an infinite loop

temporary solution:
logbook.internal.Ship.java Line 666:
while ((afterShipId != 0) && (afterShipId != 466)) { 

generic solution....need to think about it. bitmap of shipIds?

**Comment by nekopanda** [comment]
Thank you for telling me the issue and the solution. I published the new version with the temporary solution you showed. 6be2e9b8941f110fcae8dddbf37ae0f11786a828 Next, I will work on generic solution...

**Comment by nekopanda** [comment]
I implemented generic solution. 1077a755dd3b9212580fa455ca82d6f9f9098b42
