### ISSUE TITLE
Unable to sort ships by innate LoS

### ISSUE THREAD

**Issue by seishun** [nekopanda/logbook#41]
There are two 索敵 columns in the 所有艦娘一覧 window. I assume they are "innate" LoS (that is constant for a given ship, looks like "26") and "effective" LoS (that changes depending on equipment, looks like "17.1 (7.1 +10.0 + 0.0)").

The problem: if I try to sort by innate LoS, it's sorted by effective LoS instead.

Possibly related: even if I remove both 索敵 in the 列の表示非表示 window, the "effective LoS" column is still shown.

**Comment by nekopanda** [comment]
Fixed e6c53a3e1a7e43cbd64caa6c73d22ab9d72af011. Thank you for letting me know.
