### ISSUE TITLE
制空値について

### ISSUE THREAD

**Issue by Nishisonic** [nekopanda/logbook#58]
現在、制空値は搭載機数が0になっても熟練ボーナスが適用されていますが、検証によると搭載機数が0になると熟練ボーナスがなくなるみたいなので、修正をお願いします。

http://ja.kancolle.wikia.com/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89:502#5

**Comment by nekopanda** [comment]
修正しました。 760302e305ed6ac4fe5a55cad46798de400a1b7e
