### ISSUE TITLE
勝敗判定がおかしいのを直す

### ISSUE THREAD

**Issue by nekopanda** [nekopanda/logbook#66]
ver2.2.7以降、「戦況の勝敗判定がおかしいぞ！早く直せゴラァァ！」という報告が結構来てる・・・

**Comment by Nishisonic** [comment]
コメント179・・Nekopandaさんによる修正(Ver2.2.8)
>179. 名無しっぽい 2016年12月03日 13:06
>更新お疲れ様です。2.2.7への更新後に単艦オリョクルをやってて気付いたのですが
>HP9/13で小破状態の呂500を出撃させたところ、最初から減少している分のHPが
>勝敗判定の際に敵側の与えたダメージとして計算されてしまっているらしく
>ゲーム上ではノーダメかつ敵撃沈で勝利Ｂのところ、日誌側では敗北Ｄ判定になっていました

コメント189、192・・自分で修正(Ver2.2.9)
>189. 名無し 2016年12月06日 01:14
>こちらの被ダメージが1以上の極微量、おそらく1％未満で敵を全滅させた時に勝利Sではなく完全勝利Sと表示されてしまいます。
>E1とE5で見かけたので通常艦隊でも連合艦隊でも発生するようです。

>192. 名無し 2016年12月08日 10:12
>いつもお世話になっています。ver2.2.8に更新し、5－4の周回を行っていたところ、Hマスにて、2隻目のビスマルク(無改造・Lv120程度)がダメージを2受けた状態(他の艦はダメージを受けませんでした)で完全勝利と戦況の方に表示されました。イベントなどでシステムが複雑になっていますので、大変苦労されていらっしゃると思います。お忙しいと思いますが、ご報告しておきます。

コメント197・・#65 (d7e7571)で修正
>197. 名無し 2016年12月17日 17:22
>2.3.0での戦況について、敵が単艦で昼戦で撃沈状態にならない場合に勝利Aが表示されることがあります。
>実際の勝敗判定は損害比率により戦術的勝利Bか戦術的敗北Cでした。

雑な実装、すいませんでした

**Comment by nekopanda** [comment]
いえいえ、ありがとうございます！

**Comment by nekopanda** [comment]
9d4a35928c81b40edbacd082be91857d23afaeeb
