### ISSUE TITLE
2.5.2_x86版にてアプリ強制終了する

### ISSUE THREAD

**Issue by apapanda** [nekopanda/logbook#93]
[app.log](https://github.com/nekopanda/logbook/files/2262631/app.log)

戦闘ログ（50万件超え）削除で取り敢えず使えてる。

**Comment by nekopanda** [comment]
32bitだとちょっと厳しいのかもしれないので、64bit版で logbook.exe の代わりに↓これ使って試してみてください。
[logbook-win64bit-mem1gb.zip](https://github.com/nekopanda/logbook/files/2262698/logbook-win64bit-mem1gb.zip)

**Comment by nekopanda** [comment]
2GB版も作ってみた
[logbook-win64bit-mem2gb.zip](https://github.com/nekopanda/logbook/files/2262734/logbook-win64bit-mem2gb.zip)

**Comment by apapanda** [comment]
![kancolle_180807_064003_01](https://user-images.githubusercontent.com/13678934/43742726-0ee3b138-9a0e-11e8-81d7-ca143e70d36f.jpg)
取り敢えずフリーズや読み込みを諦めてしまう挙動は回避出来ているようです。
ありがとうございます。

**Comment by Rozaly** [comment]
[script.log](https://github.com/nekopanda/logbook/files/2264213/script.log)
しかし、x64版だとスクリプトとの連携がうまくいってないようです

**Comment by nekopanda** [comment]
マルチポスト？
https://github.com/Nishisonic/QuestStateEx/issues/5

このissueとは関係ないので、これで問題ないのならこのissueはcloseしようと思います。
